// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: aichat/v1/aichat.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_aichat_v1_aichat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_aichat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_aichat_v1_aichat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

// 发送消息响应
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_aichat_v1_aichat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aichat_v1_aichat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_aichat_v1_aichat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_aichat_v1_aichat_proto protoreflect.FileDescriptor

const file_aichat_v1_aichat_proto_rawDesc = "" +
	"\n" +
	"\x16aichat/v1/aichat.proto\x12\taichat.v1\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x12SendMessageRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"-\n" +
	"\x13SendMessageResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2l\n" +
	"\x06Aichat\x12b\n" +
	"\vSendMessage\x12\x1d.aichat.v1.SendMessageRequest\x1a\x1e.aichat.v1.SendMessageResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/chatB\x1dZ\x1brobot-demo/api/aichat/v1;v1b\x06proto3"

var (
	file_aichat_v1_aichat_proto_rawDescOnce sync.Once
	file_aichat_v1_aichat_proto_rawDescData []byte
)

func file_aichat_v1_aichat_proto_rawDescGZIP() []byte {
	file_aichat_v1_aichat_proto_rawDescOnce.Do(func() {
		file_aichat_v1_aichat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aichat_v1_aichat_proto_rawDesc), len(file_aichat_v1_aichat_proto_rawDesc)))
	})
	return file_aichat_v1_aichat_proto_rawDescData
}

var file_aichat_v1_aichat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aichat_v1_aichat_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: aichat.v1.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: aichat.v1.SendMessageResponse
}
var file_aichat_v1_aichat_proto_depIdxs = []int32{
	0, // 0: aichat.v1.Aichat.SendMessage:input_type -> aichat.v1.SendMessageRequest
	1, // 1: aichat.v1.Aichat.SendMessage:output_type -> aichat.v1.SendMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aichat_v1_aichat_proto_init() }
func file_aichat_v1_aichat_proto_init() {
	if File_aichat_v1_aichat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aichat_v1_aichat_proto_rawDesc), len(file_aichat_v1_aichat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aichat_v1_aichat_proto_goTypes,
		DependencyIndexes: file_aichat_v1_aichat_proto_depIdxs,
		MessageInfos:      file_aichat_v1_aichat_proto_msgTypes,
	}.Build()
	File_aichat_v1_aichat_proto = out.File
	file_aichat_v1_aichat_proto_goTypes = nil
	file_aichat_v1_aichat_proto_depIdxs = nil
}
